package mediator;

public enum Go {
	
LOGIN,
LOGINGUI_MAINGUI,
MAINGUI_LOGINGUI,
MAINGUI_NEWLOGGUI,
MAINGUI_EDITLOGGUI,

EDITLOGGUI_PROGRESSBARDIALOG,
EDITLOGGUI_MULTIPLECUSTOMERSFOREXCELDIALOG,

NEWLOGGUI_PROGRESSBARDIALOG,
NEWLOGGUI_MULTIPLECUSTOMERSFOREXCELDIALOG,

MULTIPLECUSTOMERSFOREXCELDIALOG_NEWLOGGUI,
MULTIPLECUSTOMERSFOREXCELDIALOG_EDITLOGGUI,

EXIT, MAINGUI_OPTIONSGUI, OPTIONSGUI_MAINGUI,
NEWLOGGUI_MULTIPLECUSTOMERSFOREXCELDIALOG_NEWLOGGUI,
EDITLOGGUI_MULTIPLECUSTOMERSFOREXCELDIALOG_EDITLOGGUI;

}


